### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by antoniojmsjr** [WillHubner/Horse-SocketIO#2]
Fui testar o **demo** do projeto, e ativei a variável **ReportMemoryLeaksOnShutdown** no cliente, depois de conectar no servidor finalizei o programa e recebi essa lista de memory leak.

![image](https://user-images.githubusercontent.com/20980984/110701543-09a63400-81d0-11eb-943c-a5a9b1385d5c.png)

**Comment by WillHubner** [comment]
Opa, o middleware foi reescrito
