### ISSUE TITLE
Duplicates no allowed

### ISSUE THREAD

**Issue by antoniojmsjr** [WillHubner/Horse-SocketIO#3]
Ao conectar no servidor com o mesmo **socket_user**  está gerando erro de **Duplicates no allowed**.

![image](https://user-images.githubusercontent.com/20980984/110703163-2e9ba680-81d2-11eb-9d94-ae96abf4a7ea.png)

**Comment by WillHubner** [comment]
a ideia nesse caso é não permitir mesmo 2 sockets users com mesmo nome, vou tratar a excessão,
