### ISSUE TITLE
EListError with message 'Item not found'

### ISSUE THREAD

**Issue by antoniojmsjr** [WillHubner/Horse-SocketIO#4]
Quando realizado uma requisição ao servidor e informado no header **socket_client** o nome de um cliente que não esteja na **FlistaClientes** retorna o erro de **500 internal server error**.

![image](https://user-images.githubusercontent.com/20980984/110704949-71f71480-81d4-11eb-92b8-a34bd2f8980a.png)

**Comment by WillHubner** [comment]
Resolvido!
