### ISSUE TITLE
Endpoint inválido

### ISSUE THREAD

**Issue by antoniojmsjr** [WillHubner/Horse-SocketIO#5]
Quando informado um **endpoint** inválido a requisição fica aguardando um retorno do servidor, acontece que no cliente não existe esse endpoint registrado. A função **send** fica presa no while até o cliente responder.

![image](https://user-images.githubusercontent.com/20980984/110708209-1aa77300-81d9-11eb-8f69-9c10c01df96a.png)

**Comment by WillHubner** [comment]
Corrigido, obrigado pelo feedback
